### ISSUE TITLE
Syntax for declaring runtime pip installs

### ISSUE THREAD

**Issue by cisaacstern** [pangeo-forge/meta-yaml-schema#4]
One of the[ requirements to be able to run `beam-refactor` on Pangeo Forge Cloud](https://github.com/pangeo-forge/pangeo-forge-recipes/issues/450#issuecomment-1353725197) is a `meta.yaml` syntax for declaring that we want to install `pangeo-forge-recipes` from a development branch. This is a specific (pressing) instance of the more general problem of how to support runtime pip installs.

Currently, users give something like:

```yaml
pangeo_forge_recipes: 0.9.1
```

One idea would be to have two syntaxes. A short form (as above) for the simpler case of released versions. And a long form for when we want to install from a dev branch; i.e. something like

```yaml
pangeo_forge_recipes: 
  repo: pangeo-forge/pangeo-forge-recipes
  ref: beam-refactor
```

The same logic could be extended to a new `extras_require` field, which would specify packages other than `pangeo-forge-recipes` to be pip-installed at runtime.

```yaml
extras_require:
    - pangeo-forge-runner:
        repo: pangeo-forge/pangeo-forge-runner
        ref: support-beam-refactor
```

This is all a lot easier to model in Pydantic than it is in "hand-crafted" JSON, so I'll address #3 first. Once that's resolved, we can do something like:

```python
from pydantic import BaseModel

class GithubDependency(BaseModel):
     repo: str
     ref: str

class MetaYaml(BaseModel):
    pangeo_forge_recipes: Union[str, GithubDependency]
    extras_require: Dict[str, Union[str, GithubDependency]]
    ...
```
